-- AlterTable
ALTER TABLE "Plan" ADD COLUMN     "additionalUserPrice" DOUBLE PRECISION,
ADD COLUMN     "benefits" TEXT[],
ADD COLUMN     "color" TEXT,
ADD COLUMN     "discount" DOUBLE PRECISION,
ADD COLUMN     "displayOrder" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "hasAI" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasClientPortal" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasLeadManagement" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "hasMultiChannel" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasRentalManagement" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "hasReports" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "hasSalesTools" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "hasTeamManagement" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isFeatured" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "isUnlimited" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "maxItems" INTEGER,
ADD COLUMN     "maxStorage" INTEGER,
ADD COLUMN     "maxTokens" INTEGER,
ADD COLUMN     "maxUsers" INTEGER,
ADD COLUMN     "setupFee" DOUBLE PRECISION,
ADD COLUMN     "shortDescription" TEXT;
